import { Member, Event, EmailTemplate, EmailCampaign } from '@/types'

export const mockMembers: Member[] = [
  {
    id: 'member-1',
    organizationId: 'mock-org-1',
    email: 'john.doe@example.com',
    firstName: 'John',
    lastName: 'Doe',
    role: 'admin',
    membershipType: 'professional',
    memberSince: new Date('2023-01-01'),
    subscriptionStatus: 'active',
    certifications: ['Certified Professional', 'Advanced Leadership'],
    specializations: ['Strategic Planning', 'Team Management'],
    committees: ['Executive Board', 'Strategic Planning'],
  },
  {
    id: 'member-2',
    organizationId: 'mock-org-1',
    email: 'jane.smith@example.com',
    firstName: 'Jane',
    lastName: 'Smith',
    role: 'member',
    membershipType: 'basic',
    memberSince: new Date('2023-02-15'),
    subscriptionStatus: 'active',
    certifications: ['Industry Certification'],
    specializations: ['Marketing', 'Communications'],
    committees: ['Marketing Committee'],
  },
  {
    id: 'member-3',
    organizationId: 'mock-org-1',
    email: 'bob.wilson@example.com',
    firstName: 'Bob',
    lastName: 'Wilson',
    role: 'member',
    membershipType: 'enterprise',
    memberSince: new Date('2023-03-20'),
    subscriptionStatus: 'active',
    certifications: ['Enterprise Leadership', 'Project Management'],
    specializations: ['Operations', 'Finance'],
    committees: ['Finance Committee', 'Operations Committee'],
  },
]

export const mockEvents: Event[] = [
  {
    id: 'event-1',
    organizationId: 'mock-org-1',
    title: 'Annual Industry Conference 2024',
    description: 'Join us for our annual conference featuring industry leaders and networking opportunities.',
    startDate: new Date('2024-06-15T09:00:00'),
    endDate: new Date('2024-06-17T17:00:00'),
    venue: 'Grand Hotel, New York',
    capacity: 500,
    price: 299.99,
    registrationDeadline: new Date('2024-06-01'),
    type: 'conference',
    status: 'upcoming',
    speakers: [],
    agenda: [],
    registrations: [],
  },
  {
    id: 'event-2',
    organizationId: 'mock-org-1',
    title: 'Spring Networking Mixer',
    description: 'An evening of networking and relationship building with industry peers.',
    startDate: new Date('2024-04-20T18:00:00'),
    endDate: new Date('2024-04-20T21:00:00'),
    venue: 'City Lounge, Chicago',
    capacity: 100,
    price: 49.99,
    registrationDeadline: new Date('2024-04-15'),
    type: 'networking',
    status: 'upcoming',
    speakers: [],
    agenda: [],
    registrations: [],
  },
  {
    id: 'event-3',
    organizationId: 'mock-org-1',
    title: 'Professional Development Workshop',
    description: 'Learn new skills and stay up-to-date with industry trends.',
    startDate: new Date('2024-05-10T10:00:00'),
    endDate: new Date('2024-05-10T16:00:00'),
    venue: 'Training Center, Los Angeles',
    capacity: 50,
    price: 199.99,
    registrationDeadline: new Date('2024-05-01'),
    type: 'workshop',
    status: 'upcoming',
    speakers: [],
    agenda: [],
    registrations: [],
  },
]

export const mockEmailTemplates: EmailTemplate[] = [
  {
    id: 'template-1',
    name: 'Welcome Email',
    subject: 'Welcome to {organization_name}!',
    content: 'Dear {first_name},\n\nWelcome to {organization_name}! We\'re excited to have you as a member...',
    variables: ['organization_name', 'first_name'],
    category: 'onboarding',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'template-2',
    name: 'Event Reminder',
    subject: 'Reminder: {event_name} is Coming Up!',
    content: 'Dear {first_name},\n\nThis is a reminder that {event_name} is scheduled for {event_date}...',
    variables: ['event_name', 'first_name', 'event_date'],
    category: 'events',
    isActive: true,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

export const mockEmailCampaigns: EmailCampaign[] = [
  {
    id: 'campaign-1',
    name: 'Welcome Campaign',
    subject: 'Welcome to our organization!',
    content: 'Welcome to our organization...',
    templateId: 'template-1',
    status: 'sent',
    targetAudience: ['new-members'],
    sentDate: new Date('2024-01-15T10:00:00'),
    metrics: {
      sent: 150,
      delivered: 145,
      opened: 120,
      clicked: 45,
      bounced: 5,
      unsubscribed: 2,
    },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'campaign-2',
    name: 'Event Reminder Campaign',
    subject: 'Reminder: Upcoming Event',
    content: 'Don\'t forget about our upcoming event...',
    templateId: 'template-2',
    status: 'scheduled',
    targetAudience: ['event-attendees'],
    scheduledDate: new Date('2024-03-01T09:00:00'),
    metrics: {
      sent: 0,
      delivered: 0,
      opened: 0,
      clicked: 0,
      bounced: 0,
      unsubscribed: 0,
    },
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
]

export const mockStats = {
  totalMembers: mockMembers.length,
  activeEvents: mockEvents.length,
  totalRevenue: mockEvents.reduce((sum, event) => sum + event.price, 0),
  memberEngagement: '85%',
}

export const mockActivities = [
  {
    id: '1',
    type: 'member_joined',
    title: 'New Member Joined',
    description: 'John Smith joined the organization',
    timestamp: new Date(Date.now() - 1000 * 60 * 30), // 30 minutes ago
  },
  {
    id: '2',
    type: 'event_created',
    title: 'New Event Created',
    description: 'Annual Industry Conference 2024',
    timestamp: new Date(Date.now() - 1000 * 60 * 60), // 1 hour ago
  },
  {
    id: '3',
    type: 'payment_received',
    title: 'Payment Received',
    description: 'Membership renewal payment received',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2), // 2 hours ago
  },
]
